MvcDemo/Models/Forum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcDemo.Models
{
    [Table("Forums")]
    public class Forum
    {
        [HiddenInput(DisplayValue=false)]
        public int ForumID { get; set; }
        [Required(ErrorMessage="This field is Requierd")]
        public string Title { get; set; }
        [Required(ErrorMessage = "This field is Requierd")]
        public string AddedBy { get; set; }

        // Rel
        public virtual ICollection<Post> Posts { get; set; }
    }
}

MvcDemo/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDemo.Models;
using MvcDemo.Repository;
using MvcDemo.AbstractLayer;


namespace MvcDemo.Controllers
{
    public class ForumController : Controller
    {
        private IFourmRepository repository;
        public ForumController(IFourmRepository forumRepository)
        {
            repository = forumRepository;
        }

        // ============== general action =========================
        //
        // GET: /Forum/

        public ViewResult Index()
        {
            return View(repository.GetAllForums);
        }

        [HttpGet]
        public ActionResult ViewForum(int forumId)
        {
            var forum = repository.GetForum(forumId);
            if (forum == null)
                throw new HttpException(404, "The forum could not be found");
            return View(forum);
        }

        [HttpGet]
        public ActionResult ViewPost(int postId)
        {
            var viewPost = repository.GetPost(postId);
            repository.AddViewCount(postId);
            //viewPost.ViewCount++;
            //repository.SubmitChanges();
           
            if (viewPost == null)
                throw new HttpException(404, "The post you search about could not be found!!");
            return View(viewPost);
        }

        // ================ Manage Forum ==================================
        [HttpGet]
        public ViewResult EditForum(int? forumId)
        {
            Forum forum = repository.GetAllForums.FirstOrDefault(f => f.ForumID == forumId);
            return View(forum);
        }

        [HttpPost]
        public ActionResult EditForum(Forum forum)
        {
            if (ModelState.IsValid)
            {
                repository.SaveForum(forum);
                return RedirectToAction("Index");
            }
            else
            {
                return View(forum);
            }
        }

        public ViewResult CreateForum()
        {
            return View("EditForum", new Forum());
        }

        public ActionResult RemoveForum(int forumId)
        {
            Forum deleteForum = repository.DeleteForum(forumId);
            if (deleteForum != null)
            {
                TempData["messageDelete"] = string.Format("{0} was deleted", deleteForum.Title);
            }
            return RedirectToAction("Index");
        }

        // ================= Manage Post ====================

        [HttpGet]
        public ActionResult CreatePost()
        {
          ViewBag.ForumID = new SelectList(repository.GetAllForums, "ForumID", "Title");
           return View();
       
        }

        [HttpPost]
        public ActionResult CreatePost(Post post)
        {
          if(Request.IsAjaxRequest())
          {                         
              repository.SavePost(post);
          }
          ViewBag.ForumID = new SelectList(repository.GetAllForums, "ForumID", "Title", post.ForumID);
          return PartialView("_Message");

        }

        public ActionResult ManagePosts()
        {
            var viewData = repository.GetAllPosts.Where(p => p.Approved == false);
            return View(viewData);
        }
     
        [HttpGet]
        public ActionResult ApprovePost(int postId)
        {
            Post  post = repository.ApprovePost(postId);
            if (post == null)
            {
                throw new HttpException(404, "Sorry there is no post has this ID");
            }
            return View(post);
        }

        [HttpPost]
        public ActionResult ApprovePost(int postId,FormCollection form) 
        {
            Post approvePost = repository.ApprovePost(postId);
            if (approvePost != null)
            {
                TempData["message"] = string.Format("{0} was approved", approvePost.Title);
                return RedirectToAction("ManagePosts");
            }
            else 
            {
                throw new HttpException(404, "Sorry there is no post has this ID");
            }
            
        }

        [HttpGet]
        public ActionResult RemovePost(int postId)
        {
            Post post = repository.GetPost(postId);
            if (post == null)
            {
                throw new HttpException(404, "Sorry there is no post has this ID");
            }
            return View(post);
        }

        [HttpPost]
        public ActionResult RemovePost(int postId,FormCollection form)
        {
            Post deletePost = repository.DeletePost(postId);
            if (deletePost != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletePost.Title);
                return RedirectToAction("ManagePosts");
            }
            else
            {
                throw new HttpException(404, "Sorry there is no post has this ID");
            }
        }

        // =================== Manage Comments ==================

        [HttpGet]
        public ActionResult CreateComment() 
        {
            return View();
        }

        [HttpPost]        
        public ActionResult CreateComment(Comment comment)
        {
            if (ModelState.IsValid)
            {
                repository.SaveComment(comment);
                
                return RedirectToAction("Index");
            }
            return View();
        }

        [ChildActionOnly]
        public ActionResult GetLastestPost()
        {
            var post = repository.GetAllPosts.Where(p=>p.Approved==true).OrderBy(p => p.Title).Take(5);
            return PartialView("_LastContents", post);
        }

        [ChildActionOnly]
        public ActionResult GetMuchMoreViewPost()
        {
            var postView = repository.GetAllPosts
                .OrderByDescending(x => x.ViewCount).Take(5);                                       
            return PartialView("_GetMuchMoreViewPostContents",postView);
        }
        
    }
}

MvcDemo/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDemo.AbstractLayer;
using MvcDemo.Models;

namespace MvcDemo.Controllers
{
    public class JobsController : Controller
    {
        private IJobRepository _repository;
        public JobsController(IJobRepository repository)
        {
            this._repository = repository;
        }
        //
        // GET: /Jobs/

        public ActionResult Index()
        {
            return View(_repository.GetAllJobs.Where(j => j.IsActive == true));
        }

        public ActionResult JobDetails(int jobID)
        {
            Job job = _repository.GetJob(jobID);
            if (job != null)
            {
                return View(job);
            }
            return View("Error");
        }

        public ActionResult ManageJobs()
        {
            var job = _repository.GetAllJobs;
            return View(job);
        }

        [HttpGet]
        public ActionResult CreateJob()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateJob(Job job)
        {
            if (Request.IsAjaxRequest())
            {
                _repository.SaveJob(job);
                return PartialView("_Message");
            }
            return View();
        }

        [HttpPost]
        public ActionResult RemoveJob(int jobID)
        {
            Job job = _repository.DeleteJob(jobID);
            if (job != null)
            {
                TempData["message"] = String.Format("{0} is deleted Successfully", job.Name);
                return RedirectToAction("ManageJobs");
            }
            return View();
        }

        [HttpPost]
        public ActionResult CloseJob(int jobID)
        {
            Job job = _repository.CloseJob(jobID);
             if (job != null)
            {
                TempData["message"] = String.Format("{0} is closed Successfully", job.Name);
                return RedirectToAction("ManageJobs");
            }
            return View();
        }
        
        [ChildActionOnly]
        public ActionResult GetLastestjobs()
        {
            var jobs = _repository.GetAllJobs.Where(j => j.IsActive == true).OrderBy(j => j.Name).Take(5);
            return PartialView("_LatestJobs", jobs);
        }
    }
}

MvcDemo/Views/Forum/ApprovePost.cshtml
@model MvcDemo.Models.Post

@{
    ViewBag.Title = "ApprovePost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ApprovePost</h2>

<h2>Approve Confirmation</h2>
<hr />
<p>Are you sure you want to Approve <i>@Model.Title</i></p>
<hr />
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Approve" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcDemo/Views/Forum/CreateComment.cshtml
@model MvcDemo.Models.Comment

@{
    ViewBag.Title = "CreateComment";
    Layout = null;
}


@Html.Partial("~/Views/Forum/_AddComment.cshtml")

MvcDemo/Views/Forum/CreatePost.cshtml
@model MvcDemo.Models.Post

@{
    ViewBag.Title = "CreatePost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    AjaxOptions options = new AjaxOptions();
    options.HttpMethod = "POST";
    options.InsertionMode = InsertionMode.Replace;
    options.LoadingElementId = "progress";
    options.LoadingElementDuration = 1000;
    options.UpdateTargetId = "response";
    options.OnFailure = "saveFailed";
    options.OnComplete = "saveComplete";
    options.OnSuccess = "hideImage";
}

@using (Ajax.BeginForm("CreatePost", "Forum", options))
{
    <div class="post-contents">
        <div id="post-title">
            @Html.LabelFor(m => m.Title)
            @Html.TextBoxFor(m => m.Title)
        </div>


        <div id="post-abstract">
            @Html.LabelFor(m => m.Abstract)
            @Html.TextBoxFor(m => m.Abstract)
        </div>


        <div id="post-body">
            @Html.LabelFor(m => m.Body)
            @Html.TextAreaFor(m => m.Body)
        </div>

        <div id="post-addedby">
            @Html.LabelFor(m => m.AddedBy)
            @Html.TextBoxFor(m => m.AddedBy)
        </div>

        <div id="post-formId">
            @Html.LabelFor(m => m.ForumID)
            @Html.DropDownList("ForumID", String.Empty)
        </div>

       <div id="save-post">
           <input type="submit" value="Save your post" />
       </div>                   
    </div>
    
}

<div id="progress" style="display:none;">
    <div class="modelbackgroundajaxloder">
        <img src="~/Images/ajax-loader.gif"/>
    </div>
</div>
<div id="response"></div>
@section Scripts{
    
<script src="~/Scripts/Forum.js"></script>
}


MvcDemo/Views/Forum/EditForum.cshtml
@model MvcDemo.Models.Forum

@{
    ViewBag.Title = "EditForum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditForum</h2>
@using (Html.BeginForm("EditForum","Forum")) 
{
@Html.EditorForModel();
    <input type="submit" value="Save Change" />
}

MvcDemo/Views/Forum/Index.cshtml
@model IEnumerable<MvcDemo.Models.Forum>
@using MvcDemo.Models

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="nav">
    @foreach (var f in Model)
    {
        <ul>
            <li>
                @Html.RouteLink(f.Title, "Forum", new { forumId = f.ForumID })
            </li>
        </ul>
    }

</div>
<div id="extralogo">

</div>

<div id="extrafooter">
    <div id="last-contents">
        <h2 class="heading">آخر المواضيع</h2>
 @*@Html.Partial("_LastContents",new Forum())*@
                @Html.Action("GetLastestPost")                       
    </div>

    <div id="max-readings">
        <h2 class="heading">الأكثر قراءة</h2>
        @Html.Action("GetMuchMoreViewPost")
        @*<ul>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
        </ul>*@
    </div>

    <div id="max-comments">
        <h2 class="heading">الأكثر تعليقا</h2>
        <ul>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
        </ul>
    </div>
</div>

<div id="extrafootertwo">

    <div id="our-partners">
        <h2 class="heading">شركاؤنا</h2>
        <ul>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
            <li><a href="#">Mohammed Ahmed Hussien Babiker, He Is An ASP.NET MVC Developer And He Make This PlatForm &raquo;</a></li>
        </ul>
    </div>

    <div id="jobs">
        <h2 class="heading">وظائف</h2>
       @Html.Action("GetLastestjobs","Jobs")
    </div>
</div>


MvcDemo/Views/Forum/ManagePosts.cshtml
@model IEnumerable<MvcDemo.Models.Post>

@{
    ViewBag.Title = "ManagePosts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="manage-post">
    <h2 class="heading">إدراة المنشورات</h2>
    @if (Model == null)
    {
        <p>There is no Posts yet..!!</p>
    }

    @foreach (var post in Model)
    {
        <div id="post-@post.PostID" class="post">           
            <ul>
                <li>
                    <div class="post-admin-status-approve">
                     <strong>@Html.ActionLink("Approve", "ApprovePost", new { postId = post.PostID })</strong>                         
                    </div>

                    <div class="post-admin-status-delete">
                        <strong>@Html.ActionLink("Delete", "RemovePost", new { postId = post.PostID })</strong>
                    </div>
                    
                    <div class="posted-last">
                        <strong>@post.AddedDate.ToUniversalTime(); | By @post.AddedBy</strong>                    
                    </div>
                    <h3>@post.Title</h3>

                    <a class="toggle-body" href="#">Show Body</a>
                    <div class="body" style="display:none;">
                       <h3>@post.Body</h3> 
                    </div>
                </li>
            </ul>         
        </div>     
    }
</div>


MvcDemo/Views/Forum/RemovePost.cshtml
@model MvcDemo.Models.Post

@{
    ViewBag.Title = "RemovePost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Delete Confirmation</h2>
<hr />
<p>Are you sure you want to delete <i>@Model.Title</i></p>
<hr />
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcDemo/Views/Forum/ViewForum.cshtml
@model MvcDemo.Models.Forum


@{
    ViewBag.Title = "ViewForum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="show-forum">
    <h2 class="heading"> @Model.Title</h2>
    @*@if (Model.Posts.Count == 0)
    {
        <p>Be the first one posted @@ @Model.Title</p>
    }*@
        @{
            var posts = Model.Posts.Where(p => p.Approved).OrderByDescending(p => p.AddedDate);
        }
        @foreach (var post in posts)
        {
            <ul>
                <li>
                    <div class="postView-status">
                        <strong>@post.ViewCount</strong><small>Counts</small>
                    </div>
                    <div class="postAddedBy-status">
                        <strong>By - @post.AddedBy </strong> | <strong>@post.AddedDate.ToUniversalTime()</strong>
                    </div> 

                    <h3>@Html.RouteLink(post.Title, "ForumPost", new { postId = post.PostID })</h3>
                </li>
            </ul>
           
             <div id="added-date">
                   
                </div>
        }    
</div>

MvcDemo/Views/Forum/ViewPost.cshtml
@*@model IEnumerable<MvcDemo.ViewModels.PostViewModel>*@
@model MvcDemo.Models.Post
@using MvcDemo.Models


@{
    ViewBag.Title = "ViewPost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="posts">
    <div id="@Model.PostID" class="post">
        
        <div id="subject-header">
            <div class="title-header">
            @Model.Title               
                </div>
            <div class="postViewpage-status">
                <strong>@Model.ViewCount</strong><small>View</small>
            </div>  
        </div>
        
        <div id="subject-details">
            @Model.Body
        </div>
        
    </div>
    
    <div id="post-comment">
        <h2><i>التعليقات</i></h2>
        @foreach (Comment comment in Model.Comments)
        {
            @Html.Partial("~/Views/Forum/_CommentItem.cshtml", comment);
        }
    </div>
    <hr />
    <h2>إضف تعليقك</h2>

    @*@Html.Partial("~/Views/Forum/_AddComment.cshtml", new MvcDemo.Models.Comment());*@
    @Html.Action("CreateComment", "Forum")
    <hr />
</div>


MvcDemo/Views/Forum/_AddComment.cshtml
@model MvcDemo.Models.Comment
@{
    var id = Request.Url.Segments.Last();
}
@using (Html.BeginForm("CreateComment", "Forum", FormMethod.Post))
{
  <div class="comment-contents">
      <br />
      @Html.TextBox("PostID", id, new { style = "display:none" })

      <div id="comment-title">
          @Html.LabelFor(m => m.Title)
          @Html.TextBoxFor(m => m.Title)
      </div>
      
      <div id="comment-body">
          @Html.LabelFor(m => m.Body)
          @Html.TextAreaFor(m => m.Body)
      </div>
     
      <div id="save-comment">
          <input type="submit" value="Add Comment" />
      </div>
  </div>

}

MvcDemo/Views/Forum/_CommentItem.cshtml
@model MvcDemo.Models.Comment

<div id="comment-@Model.CommentID" class="comment">
    <div class="comment-header">
        Hosted by <span class="name"><i>@Model.AddedBy</i>
           </span><small>@@ </small>
        <i>@Model.AddedDate.ToLongTimeString()</i> 
    </div>
    <blockquote class="body" style="width:900px;">@Model.Body</blockquote>
</div>
<link href="~/Content/Site.css" rel="stylesheet" />


MvcDemo/Views/Forum/_GetMuchMoreViewPostContents.cshtml
@model IEnumerable<MvcDemo.Models.Post>
<div id="max-readings">

    @foreach (var post in Model)
    {
        <ul>
            <li>
                @Html.RouteLink(post.Title, "ForumPost", new { postId = post.PostID })
            </li>
        </ul>
    }
</div>

MvcDemo/Views/Forum/_LastContents.cshtml
@model IEnumerable<MvcDemo.Models.Post>
<div id="lastposts">

 @foreach (var post in Model)
 {
     <ul>
         <li>
             @Html.RouteLink(post.Title, "ForumPost", new { postId = post.PostID })
         </li>
     </ul>       
 }
</div>





MvcDemo/Views/Forum/_Message.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div id="">
        <h3>تم حفظ البيانات بنجاح </h3>
    </div>
</body>
</html>